"""add order internal note

Revision ID: a6b24ecb4de3
Revises: aac9f87c83d3
Create Date: 2026-07-02 19:48:17.102779
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'a6b24ecb4de3'
down_revision: Union[str, Sequence[str], None] = 'aac9f87c83d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('internal_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'internal_note')
    # ### end Alembic commands ###
