"""create initial tables

Revision ID: aac9f87c83d3
Revises: 
Create Date: 2026-07-02 18:59:36.271445
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'aac9f87c83d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_normalized_name'), 'drivers', ['normalized_name'], unique=True)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('imported_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_errors_import_batch_id'), 'import_errors', ['import_batch_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('delivery_responsible_raw', sa.String(length=255), nullable=True),
    sa.Column('delivery_time', sa.Time(), nullable=True),
    sa.Column('delivery_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_careacao', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_discount', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('source_sheet', sa.String(length=255), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_driver_id'), 'orders', ['driver_id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_driver_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_import_errors_import_batch_id'), table_name='import_errors')
    op.drop_table('import_errors')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_drivers_normalized_name'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
