"""create careacao cases

Revision ID: d061c1a482e9
Revises: a6b24ecb4de3
Create Date: 2026-07-02 19:51:32.607105
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'd061c1a482e9'
down_revision: Union[str, Sequence[str], None] = 'a6b24ecb4de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('careacao_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pendente', nullable=False),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.Column('driver_response', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('pendente', 'em_tratativa', 'respondido', 'resolvido', 'cancelado')", name='ck_careacao_cases_status'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_careacao_cases_driver_id'), 'careacao_cases', ['driver_id'], unique=False)
    op.create_index(op.f('ix_careacao_cases_order_id'), 'careacao_cases', ['order_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_careacao_cases_order_id'), table_name='careacao_cases')
    op.drop_index(op.f('ix_careacao_cases_driver_id'), table_name='careacao_cases')
    op.drop_table('careacao_cases')
    # ### end Alembic commands ###
